### ISSUE TITLE
Convert goals to SMART goals

### ISSUE THREAD

**Issue by Nirvikalpa108** [FiaDanni/learningObjectives#1]
Hi @FiaDanni 

Your learning objectives are looking great! 😃 

I think we can make them even better by making them SMART. Linh Nguyen has got a lovely blog post on this, see [here](https://blog.bitsrc.io/how-to-set-objectives-as-a-software-engineer-95c58cfbaad2). Using Linh's article and my questions below, I think we can improve your goals to make them even more effective so that you achieve your target, which I'm super excited about!

1. When each day will you practice your coding? Eg will you wake up early in the morning before work, or in the evening when you get home? In your lunch break? Or perhaps weekends only? We can set our expectations now and experiment with what works best.
1. How many Exercism and Codewar exercises do you plan on doing each week? What is realistic for you? What will you do when you get stuck? Which help channels will you use?
1. How will you gain a better understanding of technical tests? How will you measure this? How will you know once you have completed this goal? When do you plan to work on this? What is your deadline?
1. When will you create a blog using your CFG skills? Will this be in Ruby? Will you use TDD to build it? Is this the project you plan on taking to Codebar each week? How long would you like to spend on it each week? 

I hope this helps! Once you have refactored your goals, you can let me know here and then we can close this issue!

**Comment by FiaDanni** [comment]
Hi @Nirvikalpa108, 

Thank you for taking the time to look at learning objectives and to even comment.

I will be taking the above in consideration to refine my goals SMART-ly. Once done, I will get back to you.

Thanks again.

**Comment by FiaDanni** [comment]
Hi @Nirvikalpa108, 

I've refined and refactored my goals as advised.  Please do have a look when you have a minute.

:)

**Comment by Nirvikalpa108** [comment]
Hi @FiaDanni I think this looks a lot better, well done! If you wanted to improve it further, you could consider switching the structure around so that you focus on your time constraint. For example:

I have 1 hour each weekday to devote to coding and 2 hours each weekend day. I will complete the following, in this order of priority:

**1 - 19 September**
1) Codebar HTML and CSS courses
2) Ruby Codeacademy
3) Ruby Codebar

**20 to 30 September**
1) Anything I haven't completed from the above
2) Ruby Exercism Hello World and 1 more challenge
3) Codewars Ruby 1 challenge
4) Flatiron School bootcamp prep

I think this might be useful, because it's clearer to see exactly what you have asked yourself to work on. Let me know your thoughts? 

When I reflect on this, I think it's over ambitious. I would move the Flatiron prep into October. I think that makes it more realistic.

How do you feel about the goals you have set yourself in September? Do you feel excited? Nervous? Are you not looking forward to it? I would be keen for us to set goals that are wholesome and feel exciting!

Looking forward to receiving your response. Good work! 😃

**Comment by FiaDanni** [comment]
Hi 👋🏾@Nirvikalpa108 ,

Thank you for raising the above issue. 

I am consistently reminding myself that this journey is a marathon and trying to do too much will not be conducive for my learning. 

My learning objectives have been now been refined and are within timeframes. I feel like these learning objectives are more achievable and manageable. ✔

As a note to myself, I have added a section for the learning objectives I would like to pursue in the future. :) 📝

If you have any further comments, please do inform me. 

Thanks again. 😊

**Comment by Nirvikalpa108** [comment]
Well Done @FiaDanni. This is looking AMAZING! I feel so proud!! 😃 Now I understand your time constraints, I also know exactly what you are working on. We are both happy that your goals look manageable and that you won't be over-working. What a fantastic set of goals. 

It would be great if you could make a note of what you achieve every week and what you struggle with? 

You could copy my sprint style, which I use wiki to record, see [here](https://github.com/Nirvikalpa108/Learning/wiki/10-June). 

You could also consider my dear friend Hanna's style of putting her weekly reflections on [Twitter](https://twitter.com/hannaaikas), which I think is amazing.

Well Done! ❤️ 
I will close this issue now, because you have excelled in your goal setting and we are good to produce excellent results in September. If you need help with anything, please reach out on Twitter or open up an Issue here if you want me to review anything 😘
